name: Deploy Portfolio

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v4

      # 2. Setup Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # 3. Install dependencies
      - run: npm ci

      # 4. Build portfolio root
      - name: Build portfolio
        run: npm run build

      # 5. Copy Valentine build into dist/projects/valentine
      - name: Copy Valentine build
        run: |
          mkdir -p dist/projects/valentine
          cp -r projects/valentine/* dist/projects/valentine/

      # 6. Custom domain
      - run: echo "icapistrano.com" > dist/CNAME

      # 7. SPA fix
      - run: cp dist/index.html dist/404.html

      # 8. Disable Jekyll
      - run: touch dist/.nojekyll

      # 9. Upload artifact
      - uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
